<html>
<head>
<title>CAPITAL</title>
</head>
<body>
<h2 style="text-align:justify"><span style="font-size:12.0pt;mso-bidi-font-size:
10.0pt"><font face="Arial" size="2">CAPITAL : </font></span></h2>
<h2 style="text-align:justify"><font face="Arial" size="2"><span style="font-size:12.0pt;mso-bidi-font-size:
10.0pt">WORK VISA</span></font></h2>
<p class="MsoNormal" style="text-align:justify">FOR APPLYING FOR A WORK VISA, 
  THE APPLICANT FIRST HAS TO GET ALL THE EDUCATIONAL AND PROFESSIONAL CERTIFICATES 
  DULY ATTESTED FROM THE <b>"MINISTRY OF HUMAN RESOURCE DEPARTMENT" - INDIA </b>AND 
  THEN FROM THE <b>"MINISTRY OF EXTERNAL AFFAIRS" - INDIA.</b> AFTER THE ATTESTATION, 
  HE / SHE CAN PERSONALLY CONTACT THE <b>"EMBASSY OF THE UNITED ARAB EMIRATES" 
  - NEW DELHI.</b> </p>
</body>
</html>
