<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF">
<table width="95%" border="0" align="center" bgcolor="#FFFFCC">
  <tr> 
    <td colspan="2"> 
      <div align="center"><b><font color="#800080" size="4" face="Arial"><u><span style="mso-bidi-font-size: 10.0pt"><font color="#000066">ACCOUNTS</font></span></u></font></b></div>
    </td>
  </tr>
  <tr> 
    <td colspan="2" height="351"> 
      <div align="justify"><font size="2" face="Arial"><b>DEAR FRIENDS<br>
        <br>
        AS THE FINANCIAL YEAR CLOSING DRAWS NEAR WE FIND GREAT PLEASURE TO LOOK 
        BACK ON THE COMPLETION OF A YEAR OF DEDICATED SERVICE TO YOU. <br>
        <br>
        LAST FINANCIAL YEAR,WE HAVE HAD MANY STAGES OF UPS AND DOWNS IN OUR INDUSTRY.LEISURE 
        SEASON WAS ALTHOUGH VERY GOOD.WE HAVE SUCCESSFULLY INCREASED OUR NUMBERS 
        FROM 40% TO 50% AS COMPARED TO LAST YEAR. WE ALSO DEALT WITH LOTS OF NEW 
        AGENTS. <br>
        <br>
        UNFORTUNATELY, WE COULD NOT CONTROL OUR CREDIT TERMS AND WE HAVE INCURRED 
        A LOSS OF ABOUT 4 LACS DUE TO NON-PAYMENT,CHEQUES GETTING BOUNCED AND 
        CLOSING DOWN OF COMPANIES .<br>
        <br>
        UPON RECONCILING OUR ACCOUNTS WE FIND THAT CERTAIN INVOICES HAVE NOT BEEN 
        CLEARED & SETTLED IN FULL DURING THE YEAR APRIL 2002 & MARCH 2003. OUR 
        COMPANY AUDITORS HAVE EMPHASISED THAT THE BALANCES SHOULD BE CLEARED NOT 
        LATER THAN 31ST MARCH SO AS TO CLOSE OUR FILES AS ON 31ST MARCH 2003 WE 
        LIKE TO APPRISE YOU THAT IF THE PAYMENTS HAVE BEEN DELAYED IN CASE OF 
        ANY DISCREPANCY OR OVERSIGHT ON EITHER PART IT SHOULD BE BROUGHT TO OUR 
        IMMEDIATE NOTICE.WE CAN ALSO FURNISH THE STATEMENT ON REQUEST AND THE 
        PAYMENT COULD BE MADE SUBSEQUENTLY. IF WE DO NOT RECEIVE ANY RESPONSE 
        FROM YOUR END WE WILL TAKE IT AS YOUR ACCEPTANCE.HOWEVER,IF WE DO NOT 
        RECEIVE OUR PAYMENTS FOR THE DELAYED INVOICES WITHIN THE DUE DATE THAT 
        IS 31ST MARCH WE SHALL BE UNABLE TO TAKE INTO ACCOUNT ANY INVOICE THEREAFTER 
        AND YOUR OFFICE WOULD BE LIABLE TO PAY THE AMOUNT FOR THE RESPECTIVE INVOICES. 
        <br>
        <br>
        WE SEEK YOUR COOPERATIONS AND REQUEST YOU TO KINDLY EXPEDITE AND FORWARD 
        THE PAYMENT DRAFT AT THE EARLIEST SO AS TO ENABLE US TO START THE FINANCIAL 
        YEAR A FRESH.<br>
        <br>
        ANTICIPATING A PROMPT RESPONSE.</b></font> </div>
    </td>
  </tr>
</table>
</body>
</html>
