<html>
<head>
<title>POE</title>
</head>
<body bgcolor="#FFFFFF">
<p align="JUSTIFY"><font size="2" face="Arial, Helvetica, sans-serif"><b>DEAR SIR 
  / MADAM, </b></font></p>
<p align="JUSTIFY"><b><font size="2" face="Arial, Helvetica, sans-serif">AS PER RECENT 
  NOTIFICATION FROM THE 'PROTECTORATE OF EMMIGRANTS' - WITH EFFECT FROM 1st NOVEMBER 
  2002, ALL PASSPORTS RECEIVED AFTER 12:30 PM WILL NOT BE PROCESSED SAME DAY FOR 
  POE STAMPING. </font></b></p>
<p align="JUSTIFY"><b><font size="2" face="Arial, Helvetica, sans-serif">REGARDS 
  </font></b></p>
<p align="JUSTIFY"><b><font size="2" face="Arial, Helvetica, sans-serif">UDAAN INDIA 
  PVT. LTD </font></b></p>
</body>
</html>
