<html>
<head>
<title>Untitled Document</title>
</head>
<body bgcolor="#FFFFFF">
<table height=309 cellspacing=0 cellpadding=0 width="100%" 
border=1 hspace="0" vspace="0" align="left">
  <tr valign="top"> 
    <td height=247> 
      <table cellspacing=0 cellpadding=0 width="99%" border=0 height="70">
        <tr> 
          <td width=0% height="73">&nbsp;</td>
          <td colspan=2 height="73"><img height=71 
            src="http://www.udaanindia.com/images/topn1.jpg" width=760></td>
        </tr>
        <tr> 
          <td width=0% height=14>&nbsp;</td>
          <td align=left bgcolor=#070692 colspan=2 height=14> 
            <div align="center"><marquee><b><i><font 
            face="Times New Roman, Times, serif"><font 
            face="Verdana, Arial, Helvetica, sans-serif"><font face="Courier New, Courier, mono" color="#FFFFFF" size="3">VISIT 
              OUR WEBSITE WITH ONLINE STATUS </font></font></font><font face="Times New Roman, Times, serif" color="#FFFFFF" size="3">"WWW.UDAANINDIA.com"</font></i></b></marquee></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height="4">&nbsp;</td>
          <td colspan=2 height="4"> 
            <div align="center"><font face="Times New Roman, Times, serif" 
            size=6><b>&nbsp;&nbsp;&nbsp;&nbsp;</b></font><b><font 
            face="Arial Black" color=#000080 size=6><i>UPDATE</i></font><i><font 
            face=Arial color=#000080 size=6> </font><font face=Arial 
            color=#000080 size=4>26th December 2002 </font></i></b></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height=108>&nbsp;</td>
          <td colspan=2 height=108> 
            <table width="100%" border="0">
              <tr> 
                <td colspan="7"><b><font color="#000080">TO. MR. RAJAN DUA</font></b></td>
              </tr>
              <tr> 
                <td colspan="7"> 
                  <hr>
                </td>
              </tr>
              <tr> 
                <td colspan="7"> 
                  <div align="center"><b><font face="Arial, Helvetica, sans-serif" color="#840084"><u><font size="4">CHINA 
                    </font></u></font></b></div>
                </td>
              </tr>
              <tr> 
                <td colspan="7">&nbsp;</td>
              </tr>
              <tr> 
                <td colspan="7" height="2"> 
                  <div align="JUSTIFY"><b><font size="2"><font face="Arial">AS 
                    PER RECENT NOTIFICATION FROM 'EMBASSY OF THE PEOPLE'S REPUBLIC 
                    OF CHINA ' - NEW DELHI, WITH EFFECT FROM <font color="#FF0033">1st 
                    JANUARY 2003</font> THE REVISED VISA FEE WILL BE AS FOLLOWS.</font></font></b> 
                  </div>
                </td>
              </tr>
              <tr> 
                <td colspan="7" height="2">&nbsp;</td>
              </tr>
              <tr bgcolor="#FF9999"> 
                <td width="12%" height="20"> 
                  <div align="center"><font size="2"><font size="2"><font face="Arial, Helvetica, sans-serif"><font face="Arial"><b></b></font></font></font></font></div>
                </td>
                <td width="13%" height="20"> 
                  <div align="center"><b><font size="2" face="Arial">SINGLE ENTRY</font></b></div>
                </td>
                <td width="16%" height="20"> 
                  <div align="center"><b><font size="2" face="Arial">DOUBLE ENTRY</font></b></div>
                </td>
                <td width="17%" height="20"> 
                  <div align="center"><b><font size="2" face="Arial">M.E. (6 MONTHS)</font></b></div>
                </td>
                <td width="17%" height="20"> 
                  <div align="center"><b><font size="2" face="Arial">M. E. (1YEAR)</font></b></div>
                </td>
                <td width="12%" height="20"> 
                  <div align="center"><b><font size="2" face="Arial">GROUP</font></b></div>
                </td>
                <td width="13%" height="20"> 
                  <div align="center"></div>
                </td>
              </tr>
              <tr bgcolor="#FFCCFF"> 
                <td width="12%" height="2" bgcolor="#FF9999"> 
                  <div align="center"><b><font size="2" face="Arial">5th Day</font></b></div>
                </td>
                <td width="13%" height="2" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 1000.00</font></b></div>
                </td>
                <td width="16%" height="2" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 1500.00</font></b></div>
                </td>
                <td width="17%" height="2" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 2000.00</font></b></div>
                </td>
                <td width="17%" height="2" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 3000.00</font></b></div>
                </td>
                <td width="12%" height="2" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS.&nbsp;&nbsp;800.00</font></b></div>
                </td>
                <td width="13%" height="2" bgcolor="#FF9999"> 
                  <div align="center"><font face="Arial, Helvetica, sans-serif" size="1">PER 
                    PERSON</font></div>
                </td>
              </tr>
              <tr bgcolor="#CCCCFF"> 
                <td width="12%" height="17" bgcolor="#FF9999"> 
                  <div align="center"><b><font size="2" face="Arial">3rd Day</font></b></div>
                </td>
                <td width="13%" height="17" bgcolor="#FFCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 1880.00</font></b></div>
                </td>
                <td width="16%" height="17" bgcolor="#FFCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 2380.00</font></b></div>
                </td>
                <td width="17%" height="17" bgcolor="#FFCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 2880.00</font></b></div>
                </td>
                <td width="17%" height="17" bgcolor="#FFCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 3880.00</font></b></div>
                </td>
                <td width="12%" height="17" bgcolor="#FFCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 1240.00</font></b></div>
                </td>
                <td width="13%" height="17" bgcolor="#FF9999"> 
                  <div align="center"><font face="Arial, Helvetica, sans-serif" size="1">PER 
                    PERSON</font></div>
                </td>
              </tr>
              <tr bgcolor="#FFCCFF"> 
                <td width="12%" height="18" bgcolor="#FF9999"> 
                  <div align="center"><b><font size="2" face="Arial">Same Day</font></b></div>
                </td>
                <td width="13%" height="18" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 2300.00</font></b></div>
                </td>
                <td width="16%" height="18" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 2800.00</font></b></div>
                </td>
                <td width="17%" height="18" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 3300.00</font></b></div>
                </td>
                <td width="17%" height="18" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 4300.00</font></b></div>
                </td>
                <td width="12%" height="18" bgcolor="#CCCCFF"> 
                  <div align="center"><b><font size="2" face="Arial">RS. 1450.00</font></b></div>
                </td>
                <td width="13%" height="18" bgcolor="#FF9999"> 
                  <div align="center"><font face="Arial, Helvetica, sans-serif" size="1">PER 
                    PERSON</font></div>
                </td>
              </tr>
              <tr bgcolor="#FFCCFF"> 
                <td colspan="7" height="18"> 
                  <div align="center"><b><font face="Arial" size="2" color="#FF0033">CHINA 
                    EMBASSY VISA SECTION WORKS ONLY ON MONDAY, WEDNESDAY AND FRIDAY.</font></b></div>
                </td>
              </tr>
              <tr> 
                <td colspan="7" height="2">&nbsp; </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr> 
          <td width=0% height=1>&nbsp;</td>
          <td colspan=2 height=1> 
            <table bordercolor=#6666ff width="100%" bgcolor=#000080 border=1>
              <tr bgcolor="#070692"> 
                <td height="2"><font face="Batang"><b><font 
                  color=#ffffff>FORWARDED BY:-</font> <font 
                  color=#ffffff>UDAAN INDIA PRIVATE LIMITED. <br>
                  CONTACT US AT:- 011-2617 7435 / 2616 0840 / 2619 6928 / 2618 
                  2402 / 2618 8075 / <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                  2618 2403 / 2610 3864. <br>
                  E.MAIL:- <a 
                  href="mailto:?To=udaan@spectranet.com&amp;subject=Re:%20UPDATE%20%201st%20December%202001"><font 
                  color=#ccffff>udaan@spectranet.com</font></a><br>
                  FOR URGENT QUERIES:- FACSIMILE : 011 - 2616 0606.</font></b></font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</html>
