<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF">
<table cellspacing=0 cellpadding=0 width="750" 
border=1 hspace="0" vspace="0" align="left" height=391>
  <tbody> 
  <tr valign="top"> 
    <td height=548> 
      <table cellspacing=0 cellpadding=0 width="99%" border=0 height="70">
        <tbody> 
        <tr> 
          <td width=0% height="73">&nbsp;</td>
          <td colspan=2 height="73"><img height=71 
            src="http://www.udaanindia.com/images/topn1.jpg" width=760></td>
        </tr>
        <tr> 
          <td width=0% height=14>&nbsp;</td>
          <td align=left bgcolor=#070692 colspan=2 height=14> 
            <div align="center"><marquee><b><i><font 
            face="Times New Roman, Times, serif"><font 
            face="Verdana, Arial, Helvetica, sans-serif"><font face="Courier New, Courier, mono" color="#FFFFFF" size="3">VISIT 
              OUR WEBSITE WITH ONLINE STATUS </font></font></font><font face="Times New Roman, Times, serif" color="#FFFFFF" size="3">"WWW.UDAANINDIA.com"</font></i></b></marquee></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height="4">&nbsp;</td>
          <td colspan=2 height="4"> 
            <div align="center"><font face="Times New Roman, Times, serif" 
            size=6><b>&nbsp;&nbsp;&nbsp;&nbsp;</b></font><b><font 
            face="Arial Black" color=#000080 size=6><i>UPDATE</i></font><i><font 
            face=Arial color=#000080 size=6> </font><font face="Arial" color="#000080" size="4">25th April 2002</font></i></b></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height=461>&nbsp;</td>
          <td colspan=2 height=461> 
            <table height=1 cellspacing=0 cellpadding=0 width="99%" 
              border=0>
              <tbody> 
              <tr> 
                <td colspan="2" height=435> 
                  <table width="754" height="398">
                    <tr> 
                      <td valign=top align=left colspan="4" height=2 width="746"><b><font color="#000080">TO. 
                        MR. RAJAN DUA</font></b></td>
                    </tr>
                    <tr> 
                      <td valign=top align=left colspan="4" height=2 width="746"> 
                        <hr>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=2>&nbsp;</td>
                      <td valign=top align=left height=2 colspan="2" width="489"> 
                        <div align="center"><b><font face="Arial, Helvetica, sans-serif" color="#840084"><u><font size="4">ONLINE 
                          STATUS CHECK</font></u></font></b></div>
                      </td>
                      <td valign=top align=left height=1 rowspan="15" width="239"> 
                        <div align="right"> <br>
                          <img src="http://www.udaanindia.com/updateimg/zim.jpg" > 
                        </div>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=2>&nbsp;</td>
                      <td valign=top align=left height=2 colspan="2" width="489">&nbsp;</td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=2>&nbsp;</td>
                      <td valign=top align=left height=2 colspan="2" width="489"> 
                        <div align="justify"><b><font face="Arial, Helvetica, sans-serif"><b><font size="2">NOW 
                          YOU CAN CHECK YOUR VISA CASES’ STATUS AND DOCUMENTATION 
                          PROCEDURES FOR VARIOUS COUNTRIES & CATEGORIES ONLINE 
                          AT WWW.UDAANINDIA.COM. <span 
                        style="mso-bidi-font-size: 10.0pt"><font color="#800080"> 
                          </font></span></font></b></font></b><font face="Arial, Helvetica, sans-serif"><b><font size="2"><span 
                        style="mso-bidi-font-size: 10.0pt"><font color="#800080"> 
                          </font></span></font></b></font></div>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=2>&nbsp;</td>
                      <td valign=top align=left height=2 colspan="2" width="489"> 
                        <div align="justify">CONTACT US FOR YOUR USER I/D AND 
                          PASSWORD, IF THE SAME HAS NOT BEEN FORWARDED TO YOU 
                          UNTILL NOW.</div>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=2>&nbsp;</td>
                      <td valign=top align=left height=2 colspan="2" width="489"> 
                        <div align="center"><b><font color="#800080" size="4" face="Arial"><u><span style="mso-bidi-font-size: 10.0pt">ZIMBABWE</span></u></font></b></div>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=2>&nbsp;</td>
                      <td valign=top align=left height=2 colspan="2" width="489"> 
                        <div align="center"> 
                          <div align="justify"><b><font size="2"><span style="mso-bidi-font-size: 10.0pt"><font face="Arial">AS 
                            PER RECENT NOTIFICATION FROM 'THE HIGH COMMISSION OF
                            THE REPUBLIC OF ZIMBABWE' - NEW DELHI, WITH EFFECT FROM
                            26th APRIL 2002 
                            THE REVISED VISA FEE WILL BE AS FOLLOWS.</font></span></font></b></div>
                        </div>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=1>&nbsp;</td>
                      <td valign=top align=left height=1 width="210"> 
                        <div align="left"><b><span 
                        style="mso-bidi-font-size: 10.0pt"><font size="2"><font color="#800080" size="4"><font face=Arial>&nbsp;&nbsp;<b><font face="Arial, Helvetica, sans-serif" size="2"><font color="#3333FF">*&nbsp;</font></font></b></font></font><font face="Arial, Helvetica, sans-serif" color="#3333FF">SINGLE
                          ENTRY VISA</font></font></span></b></div>
                      </td>
                      <td valign=top align=left height=1 width="273"><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">RS.
                        2250.00</font></b></font></td>
                    </tr>
                    <tr> 
                      <td valign=top align=right width="6" height=2></td>
                      <td valign=top align=left height=2 width="483" colspan="2">
 </td>
                    </tr>
                    <tbody> 
                    <tr> 
                      <td colspan=4 height="90" width="746"> 
                        <table width="748" border="0" align="center" height="147">
                          <tr> 
                            <td valign=top align=left colspan="6" height=2 bgcolor="#070692" width="738"><b><u><font face="Arial" color="#FFFFFF" size="4">HOLIDAYS 
                              LIST FOR &nbsp;MAY 2002.</font></u></b></td>
                          </tr>
                          <tr> 
                            <td valign=top align=left width="41" height=2 bgcolor="#FFCCCC"><u><b><font 
                        face=Courier color=#800080 size=3>DATE</font></b></u></td>
                            <td valign=top align=left width="291" height=2 bgcolor="#FFCCCC"><b><u><font face=Courier 
                        color=#800080 size=3>COUNTRY</font></u></b></td>
                            <td valign=top align=left width="42" height=2 bgcolor="#FFCCCC"><u><b><font 
                        face=Courier color=#800080 size=3>DATE</font></b></u></td>
                            <td valign=top align=left height=2 bgcolor="#FFCCCC" colspan="2" width="348"><b><u><font face=Courier 
                        color=#800080 size=3>COUNTRY</font></u></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">1<span 
                        style="mso-spacerun: yes"> &nbsp;</span>:</span></font></b></td>
                            <td valign=top align=left height=2 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">ETHIOPIA, AUSTRIA, FINLAND,
                              MALAYSIA, SPAIN, PANAMA, ARGENTINA</span></font></b></td>
                            <td valign=top align=left height=2 width="42"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black"><span 
                        style="color: black"> 20 </span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=2 colspan="2" width="348"><b><font face="Arial, Helvetica, sans-serif" size="2">AUSTRIA</font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">2&nbsp;<span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=2 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">BHUTAN, SPAIN</span></font></b></td>
                            <td valign=top align=left height=2 width="42"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">2<span 
                        style="color: black">2 </span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=2 colspan="2" width="348"><b><font face="Arial, Helvetica, sans-serif" size="2">YEMEN</font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span style="color: black">3</span><span 
                        style="COLOR: black"><span 
                        style="mso-spacerun: yes">&nbsp; </span>:</span></font></b></td>
                            <td valign=top align=left height=2 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">POLAND, ETHIOPIA, JAPAN</span></font></b></td>
                            <td valign=top align=left height=2 width="42"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">2<span 
                        style="color: black">4 </span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=2 colspan="2" width="348"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">ERITREA</span></font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">5<span 
                        style="color: black">&nbsp;</span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=4 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">ETHIOPIA</span></font></b></td>
                            <td valign=top align=left height=4 width="42" rowspan="2"><b><font face="Arial, Helvetica, sans-serif" size="2">25 
                              :</font></b></td>
                            <td valign=top align=left height=4 colspan="2" width="348" rowspan="2"><b><font face="Arial, Helvetica, sans-serif" size="2">ARGENTINA,
                              ETHIOPIA, TAIWAN, JORDAN, KOREA - REP. OF
                              (S/KOREA), M.E.A.-ATTEST., KUWAIT, MALAYSIA, INDIA</font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black"><span 
                        style="color: black"> 6 </span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=4 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">THAILAND</span></font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=13><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black"><span 
                        style="color: black"> 7 </span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=13 width="291"><font face="Arial, Helvetica, sans-serif" size="2"><b>THAILAND,
                              INDONESIA, SINGAPORE</b></font>&nbsp;</td>
                            <td valign=top align=left height=13 width="42"><b><font face="Arial, Helvetica, sans-serif" size="2">26 
                              :</font></b></td>
                            <td valign=top align=left height=13 colspan="2" width="348"><b><font face="Arial, Helvetica, sans-serif" size="2">GEORGIA,
                              ETHIOPIA, BHUTAN, TAIWAN, KOREA - REP. OF
                              (S/KOREA), M.E.A.-ATTEST.,INDIA</font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black"><span 
                        style="color: black"> 9 </span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=2 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2">THAILAND,
                              AUSTRIA</font></b></td>
                            <td valign=top align=left height=2 width="42"><b><font face="Arial, Helvetica, sans-serif" size="2">27 
                              :</font></b></td>
                            <td valign=top align=left height=2 colspan="2" width="348"><b><font face="Arial, Helvetica, sans-serif" size="2">U.S.A.,
                              THAILAND</font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">1<span 
                        style="color: black">5 </span><span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=2 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2">MALDIVES,
                              SPAIN</font></b></td>
                            <td valign=top align=left height=4 width="42"><b><font face="Arial, Helvetica, sans-serif" size="2">28 
                              :</font></b></td>
                            <td valign=top align=left height=4 colspan="2" width="348"><b><font face="Arial, Helvetica, sans-serif" size="2">ETHIOPIA</font></b></td>
                          </tr>
                          <tr bgcolor="#FEF7ED"> 
                            <td valign=top align=left width="41" height=2><b><font face="Arial, Helvetica, sans-serif" size="2"><span 
                        style="COLOR: black">17<span 
                        style="mso-spacerun: yes"> </span>:</span></font></b></td>
                            <td valign=top align=left height=2 width="291"><b><font face="Arial, Helvetica, sans-serif" size="2">NORWAY</font></b></td>
                            <td valign=top align=left height=2 width="42"><b><font face="Arial, Helvetica, sans-serif" size="2">30 
                              :</font></b></td>
                            <td valign=top align=left height=2 colspan="2" width="348"><b><font face="Arial, Helvetica, sans-serif" size="2">CROATIA,
                              AUSTRIA</font></b></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    </tbody> 
                  </table>
                </td>
              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        <tr> 
          <td width=0% height=1>&nbsp;</td>
          <td colspan=2 height=1> 
            <table bordercolor=#6666ff width="100%" bgcolor=#000080 border=1>
              <tbody> 
              <tr bgcolor="#070692"> 
                <td height="2"><font face="Batang"><b><font 
                  color=#ffffff>FORWARDED BY:-</font> <font 
                  color=#ffffff>UDAAN INDIA PRIVATE LIMITED. <br>
                  CONTACT US AT:- 011-617 7435 / 616 0840 / 619 6928 / 618 2402 
                  / 618 8075 / <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                  618 2403 / 610 3864. <br>
                  E.MAIL:- <a 
                  href="mailto:?To=udaan@spectranet.com&amp;subject=Re:%20UPDATE%20%201st%20December%202001"><font 
                  color=#ccffff>udaan@spectranet.com</font></a><br>
                  FOR URGENT QUERIES:- FACSIMILE : 011 - 616 0606.</font></b></font></td>
              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        </tbody> 
      </table>
    </td>
  </tr>
  </tbody> 
</table>
</html>
