<html><head><title></title></head><body bgcolor='#FFFFFF'>
<table width="449" border="1" align="center" bordercolor="#CCCCFF" bgcolor="#000000">
  <tr> 
    <td height="455"> 
      <table width="450" align="center" height="276">
        <tr> 
          <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/topn1small.jpg" width="450" height="42"></td>
        </tr>
        <tr> 
          <td height="2" colspan="2"> 
            <div align="center"><b><font 
            face="Arial Black" color=#000080 size=6><i><font color="#FFFF66">UPDATE</font></i></font><font color="#FFFF66"><i><font 
            face=Arial size=6> </font><font face="Arial" size="4">11th September 
              2004</font></i></font></b></div>
          </td>
        </tr>
        <tr> 
          <td height="2" colspan="2"> 
            <div align="center"><font face="Arial" size="3"><b><font size="4" color="#660000"><i><font color="#FFFFFF">TO 
              : MR. RAJAN DUA</font></i></font></b></font></div>
          </td>
        </tr>
        <tr> 
          <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/back-ground.jpg" width="450" height="1"></td>
        </tr>
        <tr> 
          <td height="22" colspan="2"> 
            <div align="center"><b><font face="Arial" size="4" color="#990099"><font color="#FFFF66">* 
              <u>UNITED KINGDOM</u> * </font></font></b></div>
          </td>
        </tr>
        <tr> 
          <td height="22" colspan="2"> 
            <div align="center"><img src="http://www.nbportal.com/incStatic/imgCountry/united-kingdom.jpg" width="400" height="250"></div>
          </td>
        </tr>
        <tr> 
          <td height="16" colspan="2"> 
            <div align="justify"><b><font face="Arial" size="2" color="#FFFFFF">AS 
              PER LATEST NOTIFICATION FROM THE "HIGH COMMISSION OF BRITAIN" - 
              NEW DELHI, FROM 1ST SEPTEMBER <font color="#FFFFCC">APPLICANT SHOULD 
              COMPLETE AN APPLICATION FORM TOGETHER WITH 2 RECENT PASSPORT SIZE 
              PHOTOGRAPHS</font>( 45 MM WIDE BY 35 MM ), RECENT AND TRUE LIKENESS, 
              SHOWING FULL FACE, WITH NO HAT, HELMET OR SUNGLASSES, ALTHOUGH APPLICANT 
              CAN WEAR EVERYDAY GLASSES, TAKEN AGAINST A WHITE BACKGROUND. THE 
              PHOTOGRAPHS SHOULD BE GLUED TO THE FORM, NOT STAPLED. <font color="#FFFFCC">(AS 
              NOW THE PHOTOGRAPH WILL BE SCANNED UPON THE VISA ITSELF)</font> 
              </font></b></div>
          </td>
        </tr>
        <tr> 
          <td height="2" colspan="2"> 
            <div align="left"><b><font face="Arial" size="4" color="#990099"><u><font color="#FFFFCC"><br>
              VFS SERVICE CHARGE RS. 441/- </font></u></font></b></div>
          </td>
        </tr>
        <tr > 
          <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/Burung.jpg" width="450" height="37"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body></html>