<html><head><title></title></head><body bgcolor='#FFFFFF'>
<table width="461" align="center" height="169" bgcolor="#D0FFD0">
  <tr> 
    <td height="2"><img src="http://www.udaanindia.com/updateimg/topn1small.jpg" width="450" height="42"></td>
  </tr>
  <tr> 
    <td height="60"> 
      <div align="center">
        <table width="99%" align="center" height="609" bgcolor="#CCFFCC">
          <tr> 
            <td height="7" bgcolor="#CCFFCC"> 
              <div align="center"><b><font 
            face="Arial Black" color=#000080 size=6><i>UPDATE</i></font><i><font 
            face=Arial color=#000080 size=6> </font><font face=Arial 
            color=#000080 size=4>25th November 2002 </font></i></b></div>
            </td>
          </tr>
          <tr> 
            <td height="7" bgcolor="#CCFFCC"> 
              <div align="center"><font face="Arial" size="3"><b><font size="4" color="#660000"><i></i></font></b></font></div>
            </td>
          </tr>
          <tr> 
            <td height="2" bgcolor="#CCFFCC"> 
              <div align="center"><b><font size="5"><i><font color="#660000" face="Arial, Helvetica, sans-serif">SAUDI 
                ARABIA </font></i></font></b></div>
            </td>
          </tr>
          <tr> 
            <td height="1"><img src="http://www.udaanindia.com/updateimg/back-ground.jpg" width="450" height="1"></td>
          </tr>
          <tr> 
            <td height="2" bgcolor="#CCFFCC"> 
              <div align="center"><b><font size="4"><i><font color="#0000FF">UPDATED 
                SAUDI ARABIA REQUIREMENTS</font></i></font></b></div>
            </td>
          </tr>
          <tr> 
            <td height="2" bgcolor="#CCFFCC"> 
              <div align="center"> 
                <p><font face="Arial" size="2"><b><font color="#660000" size="3"><i>ROYAL 
                  EMBASSY OF SAUDI ARABIA</i></font></b></font></p>
                <p align="left"><font face="Arial" size="2"><b>CHANCERY : D - 
                  12 N.D.S.E PART II, NEW DELHI 49.<br>
                  PHONE : 011 - 625 2470 / 625 2471 / 625 6419. <br>
                  FACSIMILE : 011 - 625 9333 / 625 7082. </b></font></p>
                <p align="left"><font face="Arial" size="2"><b><font size="4">BUSINESS 
                  </font></b></font></p>
              </div>
            </td>
          </tr>
          <tr> 
            <td height="129" bgcolor="#CCFFCC"> 
              <table width="99%" border="0">
                <tr> 
                  <td height="2" width="6%" valign="top" align="center">*</td>
                  <td height="2" width="94%"> 
                    <div align="JUSTIFY"><font face="Arial" size="2"><b>VALID 
                      PASSPORT ALONGWITH ALL OLD PASSPORTS.</b></font></div>
                  </td>
                </tr>
                <tr> 
                  <td height="2" width="6%" valign="top" align="center">*</td>
                  <td height="2" width="94%"> 
                    <div align="JUSTIFY"><font face="Arial" size="2"><b>1 VISA 
                      APPLICATION FORM DULY FILLED IN (PHOTOCOPY CAN BE USED).</b></font></div>
                  </td>
                </tr>
                <tr> 
                  <td height="2" width="6%" valign="top" align="center">*</td>
                  <td height="2" width="94%"> 
                    <div align="JUSTIFY"><font face="Arial" size="2"><b>2 PHOTOGRAPHS 
                      WITH WHITE BACKGROUND ONLY.</b></font></div>
                  </td>
                </tr>
                <tr> 
                  <td height="2" width="6%" valign="top" align="center">*</td>
                  <td height="2" width="94%"> 
                    <div align="JUSTIFY"><font face="Arial" size="2"><b>COVERING 
                      LETTER FROM THE COMPANY STATING APPLICANT'S NAME, DESIGNATION, 
                      PURPOSE AND DURATION OF VISIT, WITH WET SEAL AFFIXED.</b></font></div>
                  </td>
                </tr>
                <tr> 
                  <td height="2" width="6%" valign="top" align="center">*</td>
                  <td height="2" width="94%"> 
                    <div align="JUSTIFY"><font face="Arial" size="2"><b>AUTHORITY 
                      LETTER ON PAX'S BUSINESS LETTERHEAD FOR PROCESSING AND COLLECTION 
                      OF PASSPORT AFTER VISA DULY SIGNED BY APPLICANT AT THE BOTTOM 
                      (A SPACE MAY BE LEFT FOR THE NAME OF THE AUTHORISED PERSON).</b></font></div>
                  </td>
                </tr>
                <tr> 
                  <td height="2" width="6%" valign="top" align="center">*</td>
                  <td height="2" width="94%"> 
                    <div align="JUSTIFY"><font face="Arial" size="2"><b>INVITATION 
                      FROM SAUDI (PRESCRIBED FORMAT ATTACHED).<br>
                      <br>
                      TO DOWNLOAD THE INVITATION FORMAT PLEASE CLICK ON LINK <img src="http://www.ttsvisas.com/images/wwwgdl.gif"> 
                      <a href="http://www.udaanindia.com/updateimg/saudiinv.pdf" target="_blank">FORMATE</a>.</b></font></div>
                  </td>
                </tr>
                <tr> 
                  <td height="2" width="6%" valign="top" align="center">*</td>
                  <td height="2" width="94%"> 
                    <div align="JUSTIFY"><font face="Arial" size="2"><b>RECOMMENDATION 
                      FROM CHAMBER OF COMMERCE WITH WET SEAL.</b></font></div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr > 
            <td height="2" bgcolor="#CCFFCC"><font face="Arial" size="2"><b>HEALTH 
              REQUIREMENT : NIL. <br>
              <br>
              FEE : RS. 2,800/- PAYABLE IN CASH. <br>
              <br>
              TIME TAKEN : 2 - 3 DAYS. </b></font></td>
          </tr>
        </table>
      </div>
      </td>
  </tr>
  <tr > 
    <td height="2"><img src="http://www.udaanindia.com/updateimg/Burung.jpg" width="450" height="37"></td>
  </tr>
</table>
</body></html>