<html><head><title></title></head><body bgcolor='#FFFFFF'>
<table width="450" align="center" height="713" bgcolor="#BFFFFF">
  <tr> 
    <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/topn1small.jpg" width="450" height="42"></td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="center"><b><font 
            face="Arial Black" color=#000080 size=6><i>UPDATE</i></font><i><font 
            face=Arial color=#000080 size=6> </font><font face="Arial" color="#000080" size="4">15th 
        January 2003</font></i><font 
            face="Arial Black" color=#000080 size=6><i><font size="3"> </font></i></font></b></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="center"><font face="Arial" size="3"><b><font size="4" color="#660000"><i><font color="#0000FF">TO 
        : MR. RAJAN DUA</font></i></font></b></font></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/back-ground.jpg" width="450" height="1"></td>
  </tr>
  <tr bgcolor="#FFCCCC"> 
    <td height="2" colspan="2"> 
      <div align="center"><b><font color="#800080" size="4" face="Arial"><u><span style="mso-bidi-font-size: 10.0pt"><font color="#000066">GEORGIA</font></span></u></font></b></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="left"><font size="2" face="Arial"><font size="4" color="#FF6600"><b><font size="2">EMBASSY 
        OF GEORGIA</font></b></font><b><br>
        19 DDA COMPLEX, ZAMROODPUR, KAILASH COLONY, NEW DELHI.<br>
        PHONE : 26431015 / 26212605<br>
        FAX : 011-26447864<br>
        TIMINGS : 10 AM TO 5 PM / MONDAY TO FRIDAY</b></font></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="center"><b><font size="2" face="Arial"><img src="http://www.udaanindia.com/updateimg/back-ground.jpg" width="300" height="1"></font></b></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"><b><font size="2" face="Arial" color="#FF6600">BUSINESS 
      VISA REQUIREMENTS : </font></b></td>
  </tr>
  <tr> 
    <td height="251" colspan="2"> 
      <table width="100%" border="0">
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial">VALID PASSPORT </font></b></td>
        </tr>
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial">VISA APPLICATION FORM 
            DULY FILLED IN </font></b></td>
        </tr>
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial">1 PASSPORT SIZE COLOURED 
            PHOTOGRAPH </font></b></td>
        </tr>
        <tr> 
          <td width="5%" valign="top">*</td>
          <td width="95%"> 
            <p><b><font size="2" face="Arial"> COVERING LETTER FROM THE APPLICANT 
              STATING PURPOSE,&nbsp;DURATION AND DESIGNATION OF PAX ON COMPANY 
              LETTER HEAD.</font></b><b><font size="2" face="Arial"> </font></b></p>
          </td>
        </tr>
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial"> INVITATION LETTER FROM 
            GEORGIA. </font></b></td>
        </tr>
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial"> CONFIRMED AIR TICKET 
            OR AIR TICKET DETAILS. </font></b></td>
        </tr>
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial"> CONTACT PHONE NO(S) 
            OF APPLICANT. </font></b></td>
        </tr>
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial"> <font color="#FF6600">FEE 
            :</font> RS. 500/- - PAID IN CASH </font></b></td>
        </tr>
        <tr> 
          <td width="5%" valign="top" height="33">*</td>
          <td width="95%" height="33"><b><font size="2" face="Arial"> <font color="#FF6600">TIME 
            TAKEN :</font> 4 - 5 WORKING DAYS. AS APPLICATION IS REFERRED FOR 
            APPROVAL. </font></b></td>
        </tr>
        <tr> 
          <td width="5%">*</td>
          <td width="95%"><b><font size="2" face="Arial"> <font color="#FF6600">HEALTH 
            REQUIREMENTS :</font> NIL</font></b></td>
        </tr>
        <tr> 
          <td colspan="2"><b><font size="2" face="Arial"><font color="#FF6600">NOTE:</font> 
            EMBASSY GIVES ONLY BUSINESS VISA.</font></b></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <table width="100%" border="0">
        <tr> 
          <td height="2" width="25%"><b><font size="2" face="Arial"><img src="http://www.ttsvisas.com/images/wwwgdl.gif"> 
            <a href="http://www.udaanindia.com/updateimg/georgia1.pdf" target="_blank">FORM(1)</a></font></b></td>
          <td height="2" width="23%"><b><font size="2" face="Arial"><img src="http://www.ttsvisas.com/images/wwwgdl.gif"> 
            <a href="http://www.udaanindia.com/updateimg/georgia2.pdf" target="_blank">FORM(2)</a></font></b></td>
          <td height="2" width="34%"><font face="Arial" size="1">FOR DOWNLOAD 
            ACROBAT READER </font></td>
          <td height="2" width="18%"><a href="http://www.adobe.com/products/acrobat/readermain.html" target="_blank"><img src="http://images.google.com/images?q=tbn:EhR6JEY24CoC:www.websense.com/images/getacro.gif" border="0"></a></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"><b><font size="2" face="Arial"><img src="http://www.udaanindia.com/updateimg/back-ground.jpg" width="450" height="1"></font></b></td>
  </tr>
  <tr bgcolor="#FFCCCC"> 
    <td height="2" colspan="2"> 
      <div align="center"><b><font color="#800080" size="4" face="Arial"><u><span style="mso-bidi-font-size: 10.0pt"><font color="#000066">DENMARK</font></span></u></font></b></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="left"><b><font size="2"><span style="mso-bidi-font-size: 10.0pt"><font face="Arial">AS 
        PER RECENT NOTIFICATION FROM '<font color="#FF6600">ROYAL DANISH EMBASSY 
        </font>' - NEW DELHI, WITH IMMEDIATE EFFECT THE REVISED VISA FEE WILL 
        BE AS FOLLOWS.</font></span></font></b></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="center"> 
        <table width="99%" border="1" bordercolor="1">
          <tr bgcolor="#FFFFFF"> 
            <td width="59%"><b><font face="Arial" size="2">SINGLE ENTRY TILL 30 
              DAYS</font></b></td>
            <td width="41%"><b><font face="Arial" size="2">RS. 1200.00</font></b></td>
          </tr>
          <tr bgcolor="#DFFFDF"> 
            <td width="59%"><b><font face="Arial" size="2">MULTIPLE ENTRY TILL 
              90 DAYS</font></b></td>
            <td width="41%"><b><font face="Arial" size="2">RS. 1800.00</font></b></td>
          </tr>
          <tr bgcolor="#FFFFFF"> 
            <td width="59%"><b><font face="Arial" size="2">TRANSIT</font></b></td>
            <td width="41%"><b><font face="Arial" size="2">RS. &nbsp;500.00</font></b></td>
          </tr>
          <tr bgcolor="#CCFFCC"> 
            <td width="59%"><b><font face="Arial" size="2">LONG TERM MULTIPLE 
              ENTRY</font></b></td>
            <td width="41%"><b><font face="Arial" size="2">RS. 2500.00</font></b></td>
          </tr>
          <tr bgcolor="#FFFFFF"> 
            <td width="59%"><b><font face="Arial" size="2">RESIDENCE AND WORK</font></b></td>
            <td width="41%"><b><font face="Arial" size="2">RS. 2500.00</font></b></td>
          </tr>
          <tr bgcolor="#CCFFCC"> 
            <td width="59%"><b><font face="Arial" size="2">SINGLE ENTRY 30 DAYS 
              TO 90 DAYS</font></b></td>
            <td width="41%"><b><font face="Arial" size="2">RS. 1500.00</font></b></td>
          </tr>
        </table>
      </div>
    </td>
  </tr>
  <tr > 
    <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/Burung.jpg" width="450" height="37"></td>
  </tr>
</table>
</body></html>