<html><head><title></title></head><body bgcolor='#FFFFFF'>
<table width="507" align="center" height="227" bgcolor="#FFFFFF" border="1" bordercolor="#000066">
  <tr> 
    <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/topn1small.jpg" width="500" height="42"></td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="center"><b><font 
            face="Arial Black" color=#000080 size=6><i>UPDATE</i></font><i><font 
            face=Arial color=#000080 size=6> </font><font face="Arial" color="#000080" size="4">22st 
        January 2004</font></i><font 
            face="Arial Black" color=#000080 size=6><i><font size="3"> </font></i></font></b></div>
    </td>
  </tr>
  <tr> 
    <td height="2" colspan="2"> 
      <div align="center"><font face="Arial" size="3"><b><font size="4" color="#660000"><i><font color="#0000FF">TO 
        : MR. RAJAN DUA</font></i></font></b></font></div>
    </td>
  </tr>
  <tr> 
    <td height="1" colspan="2"><img src="http://www.udaanindia.com/updateimg/back-ground.jpg" width="500" height="1"></td>
  </tr>
  <tr > 
    <td height="427" colspan="2"> 
      <table width="100%" height="505">
        <tr> 
          <td valign=top align=left height=7 colspan="2"> 
            <div align="center"><img src="http://www.udaanindia.com/updateimg/canada.jpg" width="450" height="125"></div>
          </td>
        </tr>
        <tr> 
          <td valign=top align=left height=2 colspan="2"> 
            <div align="center"><b><font color="#800080" size="4" face="Arial"><u><span style="mso-bidi-font-size: 10.0pt"><font size="5">CANADA</font></span></u></font></b></div>
          </td>
        </tr>
        <tr> 
          <td valign=top align=left height=53 colspan="2"> 
            <div align="justify"><b><font size="2"><span style="mso-bidi-font-size: 10.0pt"><font face="Arial"> 
              KINDLY NOTE WITH IMMIDIATE EFFECT THE CANADIAN HIGH COMMISSION WILL 
              <font color="#FF0000">ACCEPT ONLY NEW VISA FORMS</font> (COMPLETELY 
              FILLED UP AND SIGNED BY THE APPLICANT HIMSELF) FOR ALL VISAS FAMILY 
              DETAIL SHEET IS MENDATORY. .<br>
              <br>
              YOU CAN DOWNLOAD VISA FORM FROM THE LINKS GIVEN BELOW. <br>
              <br>
              </font></span></font><font size="2" face="Arial"><img src="http://www.ttsvisas.com/images/wwwgdl.gif"><a href="http://www.udaanindia.com/forms/canada/IMM5257B.pdf" target="_blank">VISIT 
              / BUSINESS</a> &nbsp;&nbsp;<img src="http://www.ttsvisas.com/images/wwwgdl.gif"><a href="http://www.udaanindia.com/forms/canada/IMM1295B-work.pdf" target="_blank">WORK</a>&nbsp;&nbsp;&nbsp;<img src="http://www.ttsvisas.com/images/wwwgdl.gif"><a href="http://www.udaanindia.com/forms/canada/IMM1294B.pdf" target="_blank">STUDENT</a></font><font size="2"><span style="mso-bidi-font-size: 10.0pt"><font face="Arial"> 
              &nbsp;&nbsp;</font></span></font><font size="2" face="Arial"><img src="http://www.ttsvisas.com/images/wwwgdl.gif"><a href="http://www.udaanindia.com/forms/canada/canada-family-sheet.pdf" target="_blank">FAMILY 
              DETAILS</a><a href="http://www.udaanindia.com/updateimg/australia.m-67form.gif" target="_blank"><br>
              <br>
              </a></font><font size="2"><span style="mso-bidi-font-size: 10.0pt"><font face="Arial" size="2"><b>FORMS 
              CAN ALSO BE DOWNLOADED FROM <a href="http://www.cic.gc.ca" target="_blank">http://www.cic.gc.ca</a></b></font><font face="Arial"> 
              <br>
              &nbsp;<br>
              &nbsp; <br>
              <img src="http://www.udaanindia.com/images/alert1.gif" width="48" height="25"> 
              <br>
              <font color="#FF0066" size="4">PLEASE NOTE THE OLD FORMS FILLED 
              BY YOUR OFFICE WILL NOT BE ACCEPTED THEREFORE TO AVOID DELAY IN 
              PROCESSING OF THE VISAS KINDLY FORWARD CASES WITH THE NEW CANADIAN 
              FORMS ALONGWITH COMPLETE FAMILY DETAILS TO ENSURE SPEEDY PROCESSING. 
              </font></font></span></font></b></div>
          </td>
        </tr>
        <tr> 
          <td valign=top align=left height=2 colspan="2"><img src="http://www.udaanindia.com/updateimg/back-ground.jpg" width="500" height="1"></td>
        </tr>
        <tr> 
          <td valign=top align=left height=2 colspan="2">
            <div align="center"><font size="5" face="Arial" color="#800080"><b><u>TAIWAN</u></b></font></div>
          </td>
        </tr>
        <tr>
          <td valign=top align=left height=53 colspan="2">
            <div align="justify"><font face="Arial" size="2"><b>TAIWAN EMBASSY 
              REQUIRES FORMS TO BE DULY FILLED & SIGNED BY THE APPLICANT ONLY. 
              <br>
              <br>
              TO DOWNLOAD THESE FORM PLEASE CLICK ON BELOW LINK.</b></font><br>
              <br>
              <b><font size="2" face="Arial"><img src="http://www.ttsvisas.com/images/wwwgdl.gif"><a href="http://www.udaanindia.com/forms/taiwan.pdf" target="_blank">VISIT 
              / BUSINESS</a></font></b></div>
          </td>
        </tr>
        <tbody> </tbody> 
      </table>
    </td>
  </tr>
  <tr > 
    <td height="2" colspan="2"><img src="http://www.udaanindia.com/updateimg/Burung.jpg" width="498" height="37"></td>
  </tr>
</table>
<p>&nbsp;</p>
</body></html>