<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF">
<table cellspacing=0 cellpadding=0 width="400" 
border=1 hspace="0" vspace="0" align="left">
  <tbody> 
  <tr valign="top"> 
    <td> 
      <table cellspacing=0 cellpadding=0 width="99%" border=0 >
        <tbody> 
        <tr> 
          <td width=0% height="73">&nbsp;</td>
          <td colspan=2 height="73"><img height=71 
            src="http://www.udaanindia.com/images/topn1.jpg" width=760></td>
        </tr>
        <tr> 
          <td width=0% height=14>&nbsp;</td>
          <td align=left bgcolor=#070692 colspan=2 height=14> 
            <div align="center"><marquee><b><i><font 
            face="Times New Roman, Times, serif"><font 
            face="Verdana, Arial, Helvetica, sans-serif"><font face="Courier New, Courier, mono" color="#FFFFFF" size="3">VISIT 
              OUR WEBSITE WITH ONLINE STATUS </font></font></font><font face="Times New Roman, Times, serif" color="#FFFFFF" size="3">"WWW.UDAANINDIA.com"</font></i></b></marquee></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height="4">&nbsp;</td>
          <td colspan=2 height="4"> 
            <div align="center"><font face="Times New Roman, Times, serif" 
            size=6><b>&nbsp;&nbsp;&nbsp;&nbsp;</b></font><b><font 
            face="Arial Black" color=#000080 size=6><i>UPDATE</i></font><i><font 
            face=Arial color=#000080 size=6> </font><font face="Arial" color="#000080" size="4">16th 
              May 2002</font></i></b></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height=100>&nbsp;</td>
          <td colspan=2 height=100> 
            <table cellspacing=0 cellpadding=0 width="99%" 
              border=0>
              <tbody> 
              <tr> 
                <td colspan="2"> 
                  <table width="754">
                    <tr> 
                      <td valign=top align=left colspan="4" height=2><b><font color="#000080">TO. 
                        MR. RAJAN DUA</font></b></td>
                    </tr>
                    <tr> 
                      <td valign=top align=left colspan="4" height=2> 
                        <hr>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=left colspan="4" height=2> 
                        <div align="center"><b><font face="Arial, Helvetica, sans-serif" color="#840084"><u><font size="4">ONLINE 
                          STATUS CHECK</font></u></font></b></div>
                      </td>
                    </tr>
                    <tr> 
                      <td valign=top align=left colspan="4" height=2><b><font face="Arial, Helvetica, sans-serif"><b><font size="2"> 
                        <div align="justify">NOW YOU CAN CHECK YOUR VISA CASES’ 
                          STATUS AND DOCUMENTATION PROCEDURES FOR VARIOUS COUNTRIES 
                          & CATEGORIES ONLINE AT WWW.UDAANINDIA.COM. </div>
                        </font></b></font></b></td>
                    </tr>
                    <tr> 
                      <td valign=top align=left colspan="4" height=2> 
                        <div align="justify">CONTACT US FOR YOUR USER I/D AND 
                          PASSWORD, IF THE SAME HAS NOT BEEN FORWARDED TO YOU 
                          UNTILL NOW.</div>
                      </td>
                    </tr>
                    <tbody> 
                    <tr> 
                      <td colspan=4> 

                      </td>
                    </tr>

                    <tr> 
                      <td colspan=4> 
 <div align="center"><b><font face="Arial, Helvetica, sans-serif" color="#840084"><u><font size="4">SAUDI ARABIA</font></u></font></b></div><BR>
                      </td>
                    </tr>
                    <tr> 
                      <td colspan=4> <b><font face="Arial, Helvetica, sans-serif" Size="2"> 
                        <div align="justify">
AS PER RECENT NOTIFICATION FROM 'ROYAL EMBASSY OF SAUDI ARABIA' - NEW DELHI, WITH EFFECT FROM 16th MAY 2002 THE PHOTOGRAPH FOR THE VISA PROCESSING HAS TO BE 6X4 cm. IN SIZE WITH LIGHT OR WHITE BACKGROUND.</div></font></b><br>
<b><font face="Arial, Helvetica, sans-serif" Size="2"> 
                        <div align="justify">
FOR PAX TRAVELING TO SAUDI ON BUSINESS VISA THE CORRESPONDENCE ADDRESS OF THE HOST COMPANY / ORGANISATION IS MANDATORY.</div></font></b>
                      </td>
                    </tr>

                   </tbody> 
                  </table>
                </td>
              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        <tr> 
          <td width=0% height=1>&nbsp;</td>
          <td colspan=2 height=1> 
            <table bordercolor=#6666ff width="100%" bgcolor=#000080 border=1>
              <tbody> 
              <tr bgcolor="#070692"> 
                <td height="2"><font face="Batang"><b><font 
                  color=#ffffff>FORWARDED BY:-</font> <font 
                  color=#ffffff>UDAAN INDIA PRIVATE LIMITED. <br>
                  CONTACT US AT:- 011-617 7435 / 616 0840 / 619 6928 / 618 2402 
                  / 618 8075 / <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                  618 2403 / 610 3864. <br>
                  E.MAIL:- <a 
                  href="mailto:?To=udaan@spectranet.com&amp;subject=Re:%20UPDATE%20%201st%20December%202001"><font 
                  color=#ccffff>udaan@spectranet.com</font></a><br>
                  FOR URGENT QUERIES:- FACSIMILE : 011 - 616 0606.</font></b></font></td>
              </tr>
              </tbody> 
            </table>
          </td>
        </tr>
        </tbody> 
      </table>
    </td>
  </tr>
  </tbody> 
</table>
</html>
