<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF">
<table height=417 cellspacing=0 cellpadding=0 width="100%" 
border=1 hspace="0" vspace="0" align="left">
  <tr valign="top"> 
    <td height=421> 
      <table cellspacing=0 cellpadding=0 width="99%" border=0 height="70">
        <tr> 
          <td width=0% height="73">&nbsp;</td>
          <td colspan=2 height="73"><img height=71 
            src="http://www.udaanindia.com/images/topn1.jpg" width=760></td>
        </tr>
        <tr> 
          <td width=0% height=14>&nbsp;</td>
          <td align=left bgcolor=#070692 colspan=2 height=14> 
            <div align="center"><marquee><b><i><font 
            face="Times New Roman, Times, serif"><font 
            face="Verdana, Arial, Helvetica, sans-serif"><font face="Courier New, Courier, mono" color="#FFFFFF" size="3">COMING 
              SOON OUR WEBSITE WITH ONLINE HELP </font></font></font><font face="Times New Roman, Times, serif" color="#FFFFFF" size="3">"WWW.UDAANINDIA.com"</font></i></b></marquee></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height="4">&nbsp;</td>
          <td colspan=2 height="4"> 
            <div align="center"><font face="Times New Roman, Times, serif" 
            size=6><b>&nbsp;&nbsp;&nbsp;&nbsp;</b></font><b><font 
            face="Arial Black" color=#000080 size=6><i>UPDATE</i></font><i><font 
            face=Arial color=#000080 size=6> </font><font face=Arial 
            color=#000080 size=4>23rd May 2002 </font></i></b></div>
          </td>
        </tr>
        <tr> 
          <td width=0% height=307>&nbsp;</td>
          <td colspan=2 height=307> 
            <table height=1 cellspacing=0 cellpadding=0 width="99%" 
              border=0>
              <tr> 
                <td colspan="2" height=435>
                  <table width="100%" border="0">
                    <tr> 
                      <td colspan="5"><b><font color="#000080">TO. MR. RAJAN DUA</font></b></td>
                    </tr>
                    <tr> 
                      <td colspan="5"> 
                        <hr>
                      </td>
                    </tr>
                    <tr> 
                      <td rowspan="4" width="23%"><img src="http://www.udaanindia.com/updateimg/usalib.jpg" width="145" height="117"></td>
                      <td colspan="4"> 
                        <div align="center"><b><font face="Arial, Helvetica, sans-serif" color="#840084"><u><font size="4">U.S.A.</font></u></font></b></div>
                      </td>
                    </tr>
                    <tr> 
                      <td colspan="4">
                        <div align="justify"><b><font face="Arial, Helvetica, sans-serif" size="2">AS 
                          PER RECENT NOTIFICATION FROM 'AMERICAN EMBASSY' - NEW DELHI, WITH EFFECT FROM 1st JUN 2002 
                          THE APPLICATION FEES HAS BEEN CHANGED, WHILE THE VISA FEES REMAINS THE SAME.</font></b></div>
                      </td>
                    </tr>
                    <tr> 
                      <td colspan="2"><B><font color="#3333FF">&nbsp;&nbsp;* &nbsp;&nbsp;APPLICATION 
                          FEES</font></B></td>
                      <td colspan="2"><B><font color="#3333FF">Rs. 3185.00 
                          </font></B></td>
                    </tr>
                    <tr> 
                      <td colspan="2"><B><font color="#3333FF">&nbsp;&nbsp;* &nbsp;&nbsp;VISA 
                          FEES</font></B></td>
                      <td colspan="2"><B><font color="#3333FF">Rs. 3675.00 
                          </font></B></td>
                    </tr>
                    <tr> 
                      <td colspan="5"><b><font face="Arial, Helvetica, sans-serif" size="2">FEES 
                        WILL BE ACCEPTED BY DEMAND DRAFT IN FAVOUR OF 'AMERICAN EMBASSY' PAYABLE AT NEW DELHI.</font></b></td>
                    </tr>
                    <tr> 
                      <td colspan="4"> 
                        <div align="center"><b><font face="Arial, Helvetica, sans-serif" color="#840084"><u><font size="4">GREECE</font></u></font></b></div>
                      </td>
                      <td rowspan="3" width="24%" valign="top" align="right"><img src="http://www.udaanindia.com/updateimg/Greece1.jpg"></td>
                    </tr>
                    <tr> 
                      <td colspan="4">&nbsp;</td>
                    </tr>
                    <tr> 
                      <td colspan="4"><b><font face="Arial, Helvetica, sans-serif" size="2">AS 
                        PER RECENT NOTIFICATION FROM 'EMBASSY OF GREECE' - NEW 
                        DELHI, WITH IMMEDIATE EFFECT THE EMBASSY WILL BE WORKING 
                        THREE DAYS A WEEK i.e. MONDAY, WEDNESDAY AND FRIDAY.</font></b></td>
                    </tr>
                    <tr> 
                      <td rowspan="8" valign="top" width="23%"><br>
                        <img src="http://www.udaanindia.com/updateimg/netherland.jpg"></td>
                      <td colspan="4"> 
                        <div align="center"><b><font face="Arial, Helvetica, sans-serif" color="#840084"><u><font size="4">NETHERLANDS</font></u></font></b></div>
                      </td>
                    </tr>
                    <tr> 
                      <td colspan="4"><b><font face="Arial, Helvetica, sans-serif" size="2">AS 
                        PER RECENT NOTIFICATION FROM 'ROYAL NETHERLANDS EMBASSY' 
                        - NEW DELHI, THE REVISED VISA FEE WILL BE AS FOLLOWS.</font></b></td>
                    </tr>
                    <tr> 
                      <td colspan="2"><b><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">*&nbsp;&nbsp;TRANSIT</font></b></font></b></td>
                      <td colspan="2"><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">RS. 
                        &nbsp;440.00 </font></b></font></td>
                    </tr>
                    <tr> 
                      <td colspan="2" height="2"><b><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">*&nbsp;&nbsp;1 
                        MONTH SINGLE/MULTIPLE</font></b></font></b></td>
                      <td colspan="2" height="2"><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">RS. 
                        1090.00 </font></b></font></td>
                    </tr>
                    <tr> 
                      <td colspan="2"><b><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">*&nbsp;&nbsp;3 
                        MONTHS SINGLE ENTRY</font></b></font></b></td>
                      <td colspan="2"><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">RS. 
                        1310.00 </font></b></font></td>
                    </tr>
                    <tr> 
                      <td colspan="2"><b><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">*&nbsp;&nbsp;3 
                        MONTHS MULTIPLE ENETRY</font></b></font></b></td>
                      <td colspan="2"><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">RS. 
                        1530.00 </font></b></font></td>
                    </tr>
                    <tr> 
                      <td colspan="2"><b><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">*&nbsp;&nbsp;1 
                        YEAR MULTIPLE ENTRY</font></b></font></b></td>
                      <td colspan="2"><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">RS. 
                        2180.00 </font></b></font></td>
                    </tr>
                    <tr> 
                      <td colspan="2"><b><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">*&nbsp;&nbsp;LONG 
                        TERM VISA</font></b></font></b></td>
                      <td colspan="2"><font color="#3333FF"><b><font face="Arial, Helvetica, sans-serif" size="2">RS. 
                        5920.00 </font></b></font></td>
                    </tr>
                    <tr> 
                      <td colspan="5" height="2"><b><font face="Arial, Helvetica, sans-serif" size="2">FEES 
                        WILL BE ACCEPTED BY DEMAND DRAFT IN FAVOUR OF 'ROYAL NETHERLANDS 
                        EMBASSY' PAYABLE AT NEW DELHI.</font></b></td>
                    </tr>
                  </table>
                </td>
              </tr>
              <tr> </tr>
            </table>
          </td>
        </tr>
        <tr> 
          <td width=0% height=1>&nbsp;</td>
          <td colspan=2 height=1> 
            <table bordercolor=#6666ff width="100%" bgcolor=#000080 border=1>
              <tr bgcolor="#070692"> 
                <td height="2"><font face="Batang"><b><font 
                  color=#ffffff>FORWARDED BY:-</font> <font 
                  color=#ffffff>UDAAN INDIA PRIVATE LIMITED. <br>
                  CONTACT US AT:- 011-617 7435 / 616 0840 / 619 6928 / 618 2402 
                  / 618 8075 / <br>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                  618 2403 / 610 3864. <br>
                  E.MAIL:- <a 
                  href="mailto:?To=udaan@spectranet.com&amp;subject=Re:%20UPDATE%20%201st%20December%202001"><font 
                  color=#ccffff>udaan@spectranet.com</font></a><br>
                  FOR URGENT QUERIES:- FACSIMILE : 011 - 616 0606.</font></b></font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</html>
