<html> 
<p align="justify"><font face="Arial" size="2"><b>DEAR SIR/MADAM,</b><br>
  <br>
  AS PER RECENT NOTIFICATION FROM '<b>EMBASSY OF FEDERAL REPUBLIC OF GERMANY</b>' 
  - NEW DELHI, WITH IMMEDIATE EFFECT THE EMBASSY REQUIRES 2 PHOTOGRAPHS FOR TOURIST/BUSINESS 
  VISAS AND 3 PHOTOGRAPHS FOR WORK VISAS THAT SHOULD BE WITH <b>WHITE BACKGROUND</b> 
  AND <b>PASSPORT SIZE.<font color="#FF0033"> PLEASE ENCLOSE PHOTOGRAPHS IN A 
  SEPARATE COVER AS PHOTOS WITH STAPLES OR PIN MARKS WILL NOT BE ACCEPTED</font></b>. 
  </font></p>
<p><font face="Arial" size="2"><b>THANKS &amp; REGARDS</b></font></p>
<p><b><font face="Arial" size="2">UMA SHANKAR BHARDWAJ<br>
  UDAAN INDIA PVT. LTD.</font></b></p>
</html>