<!-- #include file="connection.asp" -->
<html>
<head>
<title>Udaan India Pvt. Ltd.</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="styles.css" type="text/css">
<script language="JavaScript">
<!--
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_findObj(n, d) { //v3.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
<style type="text/css">
<!--
a.ud {  font-family: Arial, Helvetica, sans-serif; font-size: 8pt; font-weight: bold; color: #333333; text-decoration: none}
a.ud:hover {  font-family: Arial, Helvetica, sans-serif; font-size: 8pt; font-weight: bold; color: #FF0000; text-decoration: none}
-->
</style>
</head>

<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" background="images/back.gif" onLoad="MM_preloadImages('images/registrationn2.gif','images/contactn2.gif','images/queriean2.gif','images/logonn2.gif','images/homen2.gif','images/profilen2.gif')">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td><img src="images/topn1.jpg" width="760" height="71"></td>
        </tr>
        <tr> 
          <td> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td width="1%"><img src="images/whitw.gif" width="13" height="20"></td>
                <td width="11%"><a href="Default.asp"><img src="images/homen1.gif" width="99" height="20" border="0" name="Image7" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image7','','images/homen2.gif',1)"></a></td>
                <td width="12%"><a href="profile.asp" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image1','','images/profilen2.gif',1)"><img src="images/profilen1.gif" width="102" height="20" name="Image1" border="0"></a></td>
                <td width="12%"><a href="update.asp"><img src="images/updaten3.gif" width="102" height="20" name="Image2" border="0"></a></td>
                <td width="12%"><a href="registration.asp"><img src="images/registrationn1.gif" width="102" height="20" name="Image3" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image3','','images/registrationn2.gif',1)" border="0"></a></td>
                <td width="12%"><a href="contactus.asp"><img src="images/contactn1.gif" width="102" height="20" name="Image4" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image4','','images/contactn2.gif',1)" border="0"></a></td>
                <td width="12%"><a href="queries.asp"><img src="images/queriean1.gif" width="101" height="20" name="Image5" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image5','','images/queriean2.gif',1)" border="0"></a></td>
                <td width="11%"><a href="logon.asp"><img src="images/logonn1.gif" width="100" height="20" name="Image6" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image6','','images/logonn2.gif',1)" border="0"></a></td>
                <td width="17%"><img src="images/pixekn.gif" width="58" height="20"></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr> 
          <td><img src="images/linecolor.gif" width="760" height="12"></td>
        </tr>
        <tr> 
          <td><img src="images/pixelb.gif" width="33" height="5"></td>
        </tr>
        <tr> 
          <td><img src="images/threei.gif" width="760" height="26" usemap="#Map" border="0"><map name="Map"><area shape="rect" coords="329,2,436,24" href="#"><area shape="rect" coords="461,1,597,24" href="#"><area shape="rect" coords="619,2,720,24" href="#"></map></td>
        </tr>
        <tr> 
          <td> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="2">&nbsp;</td>
              </tr>
              <tr> 
                <td colspan="2">
                  <table width="80%" border="0" cellpadding="1" cellspacing="1" align="center">
                    <tr> 
                      <td> 
                        <table width="75%" align="center" cellpadding="0" cellspacing="0">
                          <tr bgcolor="#FFE898"> 
                            <td height="19"> 
                              <div align="center"><b><font size="3" color="#CC0000" face="Arial, Helvetica, sans-serif"><font color="#000099"><span class="tableCaption">Updates</span> 
                                </font></font></b></div>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    <tr> 
                      <td>
                        <table width="75%" border="0" cellspacing="0" cellpadding="0">
                          <tr> 
                            <td><img src="images/linetopgreen1.gif" width="660" height="10"></td>
                          </tr>
                          <tr bgcolor="#009933"> 
                            <td> 
                              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr> 
                                  <td align="left" width="1"><img src="images/pixelsline.gif" width="1" height="7"></td>
                                  <td bgcolor="#FFFFFF"> 
                                    <table width="100%" border="0" bgcolor="#FFFFF8" cellpadding="0" cellspacing="0" background="images/backform.jpg">
                                      <tr> 
                                        <td>
                                          <table width="100%" border="0" cellspacing="1" cellpadding="1">
                                            <tr>
                                              <td align="center"><span class="WSRightBold"> We 
                                                provide the latest and dynamic 
                                                information to our users and agents.</span></td>
                                            </tr>
                                            <tr>
                                              <td>
                                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                  <tr> <%  
                date1=date()-30
                 
                 description=request.form("description")
                  
                 
                
                  set rs=server.createobject("adodb.recordset")
                  stmt="select * from dailyupdate where entrydate>'"&date1&"'"
                  rs.open stmt,con,2,3
                  if rs.eof then
                  response.write "<tr><td align='center'><span class='WSRightBold'>NO UPDATE FOUND FOR THIS MONTH.</span><td><tr>"
                  else
                  
                  while not rs.eof
                               
                %> 
                                                  <tr> 
                                                    <td colspan="2">&nbsp; 
                                                  <tr> 
                                                  <tr> 
                                                    <td>&nbsp;<span class='WebSite'><%= rs("description")%></span> 
                                                    <td> 
                                                  <tr> <%
                  rs.movenext
                  wend
                                   
                  end if
                  rs.close
                
                %> 
                                                  <tr> 
                                                    <td>&nbsp; 
                                                    <td> 
                                                  <tr> 
                                                </table>
                                              </td>
                                            </tr>
                                            <tr>
                                              <td align="center"> <span class="WSRightBold">  For 
                                                more queries contact<a href="contactus.asp"> 
                                                Udaan</a>. </span></td>
                                            </tr>
                                          </table>
                                        </td>
                                      </tr>
                                    </table>
                                  </td>
                                  <td align="right" width="1"><img src="images/pixelsline.gif" width="1" height="7"></td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                          <tr> 
                            <td><img src="images/linetopgreen2.gif" width="660" height="10"></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td>
            <!-- #include file="HomeBottom.asp" -->
            
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
