// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisaFusion.Data.Persistence;

#nullable disable

namespace VisaFusion.Data.Migrations
{
    [DbContext(typeof(VisaEntryDbContext))]
    [Migration("20260817110632_AddAdminAuditLogAndSecurityDateIndex")]
    partial class AddAdminAuditLogAndSecurityDateIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.AdminAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ActorUserId");

                    b.Property<string>("ActorUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ActorUserName");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("EventType");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Role");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TargetUserId");

                    b.Property<string>("TargetUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TargetUserName");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_adminauditlog_Date");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_adminauditlog_EventType");

                    b.ToTable("adminauditlog", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("agentsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcMgrPH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AcMgrPH");

                    b.Property<string>("Acno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acno");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("active");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Companyname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("companyname");

                    b.Property<string>("Complexname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("complexname");

                    b.Property<DateTime?>("Creationdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATIONDATE");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("DirectorPH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DirectorPH");

                    b.Property<string>("Directorname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("directorname");

                    b.Property<string>("Emailid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emailid");

                    b.Property<string>("Enteredby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enteredby");

                    b.Property<string>("Faxno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("faxno");

                    b.Property<string>("IATA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IATA");

                    b.Property<string>("Membership")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MEMBERSHIP");

                    b.Property<string>("Payment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment");

                    b.Property<string>("Phoneno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phoneno");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pincode");

                    b.Property<string>("Smsno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("smsno");

                    b.Property<string>("Street1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street1");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street2");

                    b.Property<string>("TAAI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TAAI");

                    b.Property<string>("TAFI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TAFI");

                    b.Property<string>("VisaInchargeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VisaInchargeName");

                    b.Property<string>("VisaInchargePH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VisaInchargePH");

                    b.HasKey("Id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.AgentStaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("newagentsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acno");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Companyname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("companyname");

                    b.Property<string>("Complexname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("complexname");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Directorname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("directorname");

                    b.Property<string>("Emailid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emailid");

                    b.Property<string>("Faxno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("faxno");

                    b.Property<string>("Payment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment");

                    b.Property<string>("Phoneno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phoneno");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pincode");

                    b.Property<string>("Street1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street1");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street2");

                    b.HasKey("Id");

                    b.ToTable("newagents", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Attestation", b =>
                {
                    b.Property<int>("AttestationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttestationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttestationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("AttestationId");

                    b.ToTable("Attestation", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.AwbLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Agentsid")
                        .HasColumnType("int")
                        .HasColumnName("agentsid");

                    b.Property<string>("Awb")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("awb");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<string>("Toemail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("toemail");

                    b.HasKey("Id");

                    b.HasIndex("Agentsid")
                        .HasDatabaseName("IX_sentawb_agentsid");

                    b.ToTable("sentawb", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Bank", b =>
                {
                    b.Property<int>("Bankid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bankid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bankid"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("Bankid");

                    b.ToTable("bank", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Cab", b =>
                {
                    b.Property<int>("Cabid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cabid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cabid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("Cabid");

                    b.ToTable("cab", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("certificateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("CertificateId");

                    b.ToTable("certificate", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.ContentUpdate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("Entrydate")
                        .HasColumnType("datetime2")
                        .HasColumnName("entrydate");

                    b.HasKey("Id");

                    b.ToTable("dailyUpdate", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.CountryInfo", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("About");

                    b.Property<string>("Climate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Climate");

                    b.Property<string>("ContinentFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Continent_File");

                    b.Property<string>("Curency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Curency");

                    b.Property<string>("FlagFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Flag_File");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Language");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Religion");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TimeZone");

                    b.Property<string>("VisaFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Visa_File");

                    b.HasKey("CountryId");

                    b.ToTable("CountryInfo", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.DeletedItemAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Countryid")
                        .HasColumnType("int")
                        .HasColumnName("countryid");

                    b.Property<string>("Deletedby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deletedby");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Paxid")
                        .HasColumnType("int")
                        .HasColumnName("paxid");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.HasKey("Id");

                    b.ToTable("deleteditem", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.EmailLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Agentsid")
                        .HasColumnType("int")
                        .HasColumnName("agentsid");

                    b.Property<string>("Awb")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("awb");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Toemail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("toemail");

                    b.HasKey("Id");

                    b.HasIndex("Agentsid")
                        .HasDatabaseName("IX_sentmails_agentsid");

                    b.ToTable("sentmails", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Embassy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmbassyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("active");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("Chancery")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chancery");

                    b.Property<string>("Chanceryaddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chanceryaddress");

                    b.Property<string>("Chanceryphone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chanceryphone");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Emailid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emailid");

                    b.Property<string>("Embassyname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("embassyname");

                    b.Property<string>("Faxno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("faxno");

                    b.Property<string>("Phoneno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phoneno");

                    b.Property<string>("Street1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street1");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street2");

                    b.Property<string>("Workinghours")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("workinghours");

                    b.HasKey("Id");

                    b.ToTable("embassy", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Entry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Agent")
                        .HasColumnType("int")
                        .HasColumnName("agent");

                    b.Property<string>("AgentInstruction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AgentInstruction");

                    b.Property<int?>("Attestation")
                        .HasColumnType("int")
                        .HasColumnName("attestation");

                    b.Property<string>("Bill")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bill");

                    b.Property<int?>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<DateTime?>("Coldate")
                        .HasColumnType("datetime2")
                        .HasColumnName("coldate");

                    b.Property<string>("Companyname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("companyname");

                    b.Property<DateTime?>("Dateofbirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("Enteredby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("enteredby");

                    b.Property<int?>("Entries")
                        .HasColumnType("int")
                        .HasColumnName("entries");

                    b.Property<DateTime?>("Entrydatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("entrydatetime");

                    b.Property<int?>("Entrytype")
                        .HasColumnType("int")
                        .HasColumnName("entrytype");

                    b.Property<string>("Externalremark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("externalremark");

                    b.Property<string>("Internalremark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("internalremark");

                    b.Property<string>("Passportno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passportno");

                    b.Property<string>("Paxname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paxname");

                    b.Property<int?>("Poe")
                        .HasColumnType("int")
                        .HasColumnName("poe");

                    b.Property<DateTime?>("Receivedate")
                        .HasColumnType("datetime2")
                        .HasColumnName("receivedate");

                    b.Property<string>("Refferer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refferer");

                    b.Property<int?>("Refno")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sentDate");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Subdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("subdate");

                    b.Property<int?>("Totalpassengers")
                        .HasColumnType("int")
                        .HasColumnName("totalpassengers");

                    b.Property<DateTime?>("Traveldate")
                        .HasColumnType("datetime2")
                        .HasColumnName("traveldate");

                    b.HasKey("Id");

                    b.HasAlternateKey("Refno")
                        .HasName("IX_Mainentry_refno");

                    b.HasIndex("Agent")
                        .HasDatabaseName("IX_Mainentry_agent");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Mainentry_category");

                    b.HasIndex("Entrytype")
                        .HasDatabaseName("IX_Mainentry_entrytype");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Mainentry_status");

                    b.ToTable("Mainentry", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.EntryAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bighistoryid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Agent")
                        .HasColumnType("int")
                        .HasColumnName("agent");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remarks");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Refno")
                        .HasDatabaseName("IX_bighistory_refno");

                    b.ToTable("bighistory", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.EntryPassenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaxID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Passportno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passportno");

                    b.Property<string>("Paxname")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Paxname");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<int?>("Totalpax")
                        .HasColumnType("int")
                        .HasColumnName("totalpax");

                    b.HasKey("Id");

                    b.HasIndex("Paxname")
                        .HasDatabaseName("IX_entryDetails_Paxname");

                    b.HasIndex("Refno")
                        .HasDatabaseName("IX_entryDetails_refno");

                    b.ToTable("entryDetails", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.EntryType", b =>
                {
                    b.Property<int>("EntryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EntryTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryTypeId"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("EntryTypeId");

                    b.ToTable("EntryType", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Holiday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("countryID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("HolidayDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("holiday");

                    b.HasKey("Id");

                    b.ToTable("holidaylist", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Hotel", b =>
                {
                    b.Property<int>("Hotelid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hotelid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hotelid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("Hotelid");

                    b.ToTable("hotel", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Attestfee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("attestfee");

                    b.Property<string>("Attestremark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attestremark");

                    b.Property<decimal?>("Cabfee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("cabfee");

                    b.Property<decimal?>("Courierfee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("courierfee");

                    b.Property<decimal?>("Grandtotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("grandtotal");

                    b.Property<decimal?>("Hotelfee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("hotelfee");

                    b.Property<DateTime?>("Invoicedate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoicedate");

                    b.Property<int?>("Invoiceno")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("invoiceno");

                    b.Property<string>("Invtype")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("invtype");

                    b.Property<decimal?>("Misc")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("misc");

                    b.Property<string>("Miscremark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("miscremark");

                    b.Property<decimal?>("Poe")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("poe");

                    b.Property<string>("Poeremark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("poeremark");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.HasKey("Id");

                    b.HasAlternateKey("Invoiceno")
                        .HasName("IX_invoice_invoiceno");

                    b.HasIndex("Refno")
                        .HasDatabaseName("IX_invoice_refno");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.InvoiceDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Countryid")
                        .HasColumnType("int")
                        .HasColumnName("countryid");

                    b.Property<decimal?>("Ddcharges")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("ddcharges");

                    b.Property<decimal?>("Handlingfee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("handlingfee");

                    b.Property<int?>("Invoiceno")
                        .HasColumnType("int")
                        .HasColumnName("invoiceno");

                    b.Property<string>("Invtype")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("invtype");

                    b.Property<int?>("Paxid")
                        .HasColumnType("int")
                        .HasColumnName("paxid");

                    b.Property<decimal?>("VFSTTCharges")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("VFSTTCharges");

                    b.Property<decimal?>("Visafee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("visafee");

                    b.HasKey("Id");

                    b.HasIndex("Invoiceno")
                        .HasDatabaseName("IX_invoicedetail_invoiceno");

                    b.ToTable("invoicedetail", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.LedgerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("agentID");

                    b.Property<decimal?>("Balance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("balance");

                    b.Property<int?>("Bank")
                        .HasColumnType("int")
                        .HasColumnName("bank");

                    b.Property<decimal?>("Credit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("credit");

                    b.Property<string>("Dddate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dddate");

                    b.Property<string>("Ddno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ddno");

                    b.Property<decimal?>("Debit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("Debit");

                    b.Property<DateTime?>("EntrydateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("entrydateTime");

                    b.Property<int?>("Invno")
                        .HasColumnType("int")
                        .HasColumnName("invno");

                    b.Property<string>("Paidas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paidas");

                    b.Property<string>("Paxname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paxname");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<string>("Reftype")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reftype");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transactionType");

                    b.Property<DateTime?>("Transdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transdate");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.ToTable("Ledger", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.MasterBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Agentid")
                        .HasColumnType("int")
                        .HasColumnName("agentid");

                    b.Property<DateTime?>("Duedate")
                        .HasColumnType("datetime2")
                        .HasColumnName("duedate");

                    b.Property<decimal?>("Masterbalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("masterbalance");

                    b.HasKey("Id");

                    b.ToTable("masterbalance", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.PaxAttestation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AttestationId")
                        .HasColumnType("int")
                        .HasColumnName("AttestationID");

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int")
                        .HasColumnName("CertificateID");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<int?>("PaxId")
                        .HasColumnType("int")
                        .HasColumnName("PaxID");

                    b.HasKey("Id");

                    b.HasIndex("AttestationId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("PaxId");

                    b.ToTable("PaxAttestation", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.PaxCab", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ac")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ac");

                    b.Property<string>("Actualhour")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("actualhour");

                    b.Property<int?>("Actualkm")
                        .HasColumnType("int")
                        .HasColumnName("actualkm");

                    b.Property<string>("Cabno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cabno");

                    b.Property<string>("Cabowner")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cabowner");

                    b.Property<string>("Dest")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dest");

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("datetime2")
                        .HasColumnName("enddate");

                    b.Property<DateTime?>("EntryDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("entryDateTime");

                    b.Property<int?>("Extraamount")
                        .HasColumnType("int")
                        .HasColumnName("extraamount");

                    b.Property<string>("Extrahour")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extrahour");

                    b.Property<string>("Extrainfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extrainfo");

                    b.Property<int?>("Extrakm")
                        .HasColumnType("int")
                        .HasColumnName("extrakm");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Noofday")
                        .HasColumnType("int")
                        .HasColumnName("noofday");

                    b.Property<string>("Orderedby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orderedby");

                    b.Property<int?>("Ratesperday")
                        .HasColumnType("int")
                        .HasColumnName("ratesperday");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<DateTime?>("Sdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sdate");

                    b.Property<string>("Standeredhour")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("standeredhour");

                    b.Property<int?>("Standeredkm")
                        .HasColumnType("int")
                        .HasColumnName("standeredkm");

                    b.Property<string>("Startfrom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("startfrom");

                    b.Property<int?>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<string>("Vehical")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vehical");

                    b.HasKey("Id");

                    b.ToTable("paxCab", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.PaxCountryStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<string>("Colcheck")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("colcheck");

                    b.Property<DateTime?>("Coldate")
                        .HasColumnType("datetime2")
                        .HasColumnName("coldate");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<decimal?>("Couriercharges")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("couriercharges");

                    b.Property<decimal?>("Ddcharges")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("ddcharges");

                    b.Property<DateTime?>("Entrydatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("entrydatetime");

                    b.Property<int?>("Entrytype")
                        .HasColumnType("int")
                        .HasColumnName("entrytype");

                    b.Property<decimal?>("Handlingfee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("handlingfee");

                    b.Property<decimal?>("Misccharges")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("Misccharges");

                    b.Property<int?>("PaxId")
                        .HasColumnType("int")
                        .HasColumnName("PaxID");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sentDate");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    b.Property<DateTime?>("Subdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("subdate");

                    b.Property<decimal?>("Total")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("total");

                    b.Property<decimal?>("VFSTTCharges")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("VFSTTCharges");

                    b.Property<decimal?>("Visafee")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("visafee");

                    b.HasKey("Id");

                    b.HasIndex("PaxId")
                        .HasDatabaseName("IX_PaxStatus_PaxID");

                    b.HasIndex("Refno")
                        .HasDatabaseName("IX_PaxStatus_refno");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_PaxStatus_statusID");

                    b.ToTable("PaxStatus", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.PaxHotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Arrivaldate")
                        .HasColumnType("datetime2")
                        .HasColumnName("arrivaldate");

                    b.Property<string>("Arrivaltime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("arrivaltime");

                    b.Property<DateTime?>("Departdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("departdate");

                    b.Property<string>("Departtime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("departtime");

                    b.Property<DateTime?>("EntryDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("entryDateTime");

                    b.Property<string>("Flightdetail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("flightdetail");

                    b.Property<string>("Flightstatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("flightstatus");

                    b.Property<int?>("Hotelname")
                        .HasColumnType("int")
                        .HasColumnName("hotelname");

                    b.Property<int?>("Misccharges")
                        .HasColumnType("int")
                        .HasColumnName("misccharges");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Noofrooms")
                        .HasColumnType("int")
                        .HasColumnName("noofrooms");

                    b.Property<int?>("Nosofdays")
                        .HasColumnType("int")
                        .HasColumnName("nosofdays");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<int?>("Tariff")
                        .HasColumnType("int")
                        .HasColumnName("tariff");

                    b.Property<int?>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<string>("Transportation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transportation");

                    b.HasKey("Id");

                    b.ToTable("paxhotel", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Poe", b =>
                {
                    b.Property<int>("PoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PoeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoeId"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("PoeId");

                    b.ToTable("Poe", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.PriWork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<DateTime?>("Edate")
                        .HasColumnType("datetime2")
                        .HasColumnName("edate");

                    b.Property<string>("Givenby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("givenby");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Work")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("work");

                    b.HasKey("Id");

                    b.ToTable("priwork", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Scheduler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("messageid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Messagefrom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messagefrom");

                    b.Property<string>("Messageread")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messageread");

                    b.Property<string>("Messageto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messageto");

                    b.Property<DateTime?>("Sentdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sentdate");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("scheduler", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.SecurityDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Closedby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("closedby");

                    b.Property<DateTime?>("Closingtime")
                        .HasColumnType("datetime2")
                        .HasColumnName("closingtime");

                    b.Property<DateTime?>("Date1")
                        .HasColumnType("datetime2")
                        .HasColumnName("date1");

                    b.Property<string>("Openby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("openby");

                    b.Property<DateTime?>("Openingtime")
                        .HasColumnType("datetime2")
                        .HasColumnName("openingtime");

                    b.HasKey("Id");

                    b.HasIndex("Date1")
                        .IsUnique()
                        .HasDatabaseName("IX_security_date1")
                        .HasFilter("[date1] IS NOT NULL");

                    b.ToTable("security", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.SmsLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("agentID");

                    b.Property<string>("Cellno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cellno");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Paxname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paxname");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<string>("Sentby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentby");

                    b.Property<DateTime?>("Sentdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sentdate");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_smshistory_agentID");

                    b.HasIndex("Refno")
                        .HasDatabaseName("IX_smshistory_refno");

                    b.ToTable("smshistory", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.SmsQueue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("agentID");

                    b.Property<string>("Cellno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cellno");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Message");

                    b.Property<string>("Paxname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paxname");

                    b.Property<int?>("Refno")
                        .HasColumnType("int")
                        .HasColumnName("refno");

                    b.Property<string>("Sentby")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentby");

                    b.Property<DateTime?>("Sentdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("sentdate");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_smsQueue_agentID");

                    b.ToTable("smsQueue", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("StatusId");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.StatusHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<int?>("PaxId")
                        .HasColumnType("int")
                        .HasColumnName("PaxID");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remarks");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_StatusHistory_Date");

                    b.HasIndex("PaxId")
                        .HasDatabaseName("IX_StatusHistory_PaxID");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_StatusHistory_StatusID");

                    b.ToTable("StatusHistory", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Subscriber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("subscriber", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.VisaInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryID");

                    b.Property<int?>("CountryFor")
                        .HasColumnType("int")
                        .HasColumnName("countryFor");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("countryID");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("information");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("VisaInfo", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.WeeklyOff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Embassyid")
                        .HasColumnType("int")
                        .HasColumnName("embassyid");

                    b.Property<int?>("Weekend")
                        .HasColumnType("int")
                        .HasColumnName("weekend");

                    b.HasKey("Id");

                    b.HasIndex("Embassyid");

                    b.ToTable("weeklyoff", (string)null);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.Entry", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("Agent")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisaFusion.Data.Persistence.Entities.EntryType", null)
                        .WithMany()
                        .HasForeignKey("Entrytype")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.EntryPassenger", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("Refno")
                        .HasPrincipalKey("Refno")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("Invoiceno")
                        .HasPrincipalKey("Invoiceno")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.PaxAttestation", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Attestation", null)
                        .WithMany()
                        .HasForeignKey("AttestationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisaFusion.Data.Persistence.Entities.Certificate", null)
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisaFusion.Data.Persistence.Entities.EntryPassenger", null)
                        .WithMany()
                        .HasForeignKey("PaxId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.PaxCountryStatus", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("Refno")
                        .HasPrincipalKey("Refno")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisaFusion.Data.Persistence.Entities.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.SmsQueue", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.StatusHistoryEntry", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.VisaInfo", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VisaFusion.Data.Persistence.Entities.WeeklyOff", b =>
                {
                    b.HasOne("VisaFusion.Data.Persistence.Entities.Embassy", null)
                        .WithMany()
                        .HasForeignKey("Embassyid")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
