using System.Collections;
using System.Data;
using System.Data.Common;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging;
using VisaFusion.Migration.Catalog;

namespace VisaFusion.Migration.Copy;

/// <summary>Result of copying one table.</summary>
public sealed record CopyResult(string LegacyTable, long RowsCopied, bool IdentityPreserved);

/// <summary>
/// Batch copy engine (SPEC-0004 T025, T026; spec §13, FR-002).
///
/// Copies legacy tables to the target in FK-dependency order (parents first,
/// enforced by <see cref="TableCatalog"/> ordering). Uses SqlBulkCopy with
/// bounded batch sizes; identity columns are preserved via IDENTITY_INSERT
/// (FR-003) when the legacy table has an identity column, and surrogate identity
/// columns (target-only) are excluded from the mapping so the target generates
/// them. Only parameterized/derived column metadata is used — no
/// string-concatenated SQL with user input (NFR-003).
/// </summary>
public sealed class BulkCopyEngine
{
    private readonly string _legacyConnectionString;
    private readonly string _targetConnectionString;
    private readonly int _batchSize;
    private readonly ILogger _logger;

    public BulkCopyEngine(string legacyConnectionString, string targetConnectionString, int batchSize,
        ILogger logger)
    {
        _legacyConnectionString = legacyConnectionString;
        _targetConnectionString = targetConnectionString;
        _batchSize = batchSize;
        _logger = logger;
    }

    /// <summary>
    /// Copies one table. Throws on failure (step failure, exit 2).
    /// When <paramref name="transform"/> is provided, the source SELECT is
    /// wrapped so the rows written exactly match what the target schema
    /// accepts (e.g. deduplication for a documented PK-collapsing rule).
    /// </summary>
    public async Task<CopyResult> CopyAsync(TableSpec spec, CopyTransform? transform = null, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(spec.TargetTable);

        await using var source = new SqlConnection(_legacyConnectionString);
        await source.OpenAsync(ct);
        await using var target = new SqlConnection(_targetConnectionString);
        await target.OpenAsync(ct);

        // Columns to copy: legacy data columns. When the table preserves its
        // legacy identity (spec.IdentityColumn set), the identity column MUST be
        // part of the copy set so values round-trip via IDENTITY_INSERT (FR-003).
        // Surrogate-key tables have no legacy identity column, so their target
        // surrogate is excluded from the mapping and generated by the target.
        var keepIdentity = spec.IdentityColumn is not null;
        var dataColumns = await LegacyDataColumnsAsync(source, spec.LegacyTable, includeIdentity: keepIdentity, ct);

        if (keepIdentity)
        {
            if (!dataColumns.Contains(spec.IdentityColumn!, StringComparer.OrdinalIgnoreCase))
                throw new InvalidOperationException(
                    $"Identity column '{spec.IdentityColumn}' not found in legacy '{spec.LegacyTable}'.");
            await EnableIdentityInsertAsync(target, spec.TargetTable, true, ct);
        }

        try
        {
            using var copy = new SqlBulkCopy(target, SqlBulkCopyOptions.KeepIdentity, null)
            {
                DestinationTableName = spec.TargetTable,
                BatchSize = _batchSize,
                BulkCopyTimeout = 0
            };

            foreach (var col in dataColumns)
                copy.ColumnMappings.Add(col, col);

            await using var reader = await ReadRowsAsync(source, spec.LegacyTable, dataColumns, transform, ct);
            await copy.WriteToServerAsync(reader, ct);

            return new CopyResult(spec.LegacyTable, reader.RowsRead, keepIdentity);
        }
        finally
        {
            if (keepIdentity)
                await EnableIdentityInsertAsync(target, spec.TargetTable, false, ct);
        }
    }

    /// <summary>
    /// Reads legacy data columns by name. When <paramref name="includeIdentity"/>
    /// is true (identity-preserving table), the legacy identity column is included
    /// so its values are copied and written with IDENTITY_INSERT. Surrogate-key
    /// tables exclude identity columns (none exist in the legacy schema anyway);
    /// the target generates its own surrogate.
    /// </summary>
    private static async Task<List<string>> LegacyDataColumnsAsync(SqlConnection source, string legacyTable,
        bool includeIdentity, CancellationToken ct)
    {
        var sql = @"
            SELECT c.COLUMN_NAME
              FROM INFORMATION_SCHEMA.COLUMNS c
             WHERE c.TABLE_NAME = @table
               AND (@includeIdentity = 1
                    OR COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)),
                                      c.COLUMN_NAME, 'IsIdentity') = 0)
             ORDER BY c.ORDINAL_POSITION";
        await using var cmd = source.CreateCommand();
        cmd.CommandText = sql;
        cmd.Parameters.AddWithValue("@table", legacyTable);
        cmd.Parameters.AddWithValue("@includeIdentity", includeIdentity);
        var cols = new List<string>();
        await using (var r = await cmd.ExecuteReaderAsync(ct))
        {
            while (await r.ReadAsync(ct)) cols.Add(r.GetString(0));
        }
        return cols;
    }

    /// <summary>
    /// Opens a streaming reader over the source rows (read-only). When a
    /// <see cref="CopyTransform"/> is supplied, the transform wraps the plain
    /// column SELECT (e.g. deduplication via ROW_NUMBER); the outer projection
    /// still exposes exactly the same column list, so the bulk-copy mapping is
    /// unaffected.
    /// </summary>
    private static async Task<CountingDataReader> ReadRowsAsync(SqlConnection source, string legacyTable,
        IReadOnlyList<string> columns, CopyTransform? transform, CancellationToken ct)
    {
        var columnList = string.Join(", ", columns.Select(c => "[" + c.Replace("]", "]]", StringComparison.Ordinal) + "]"));
        // Ownership of the command is transferred to CountingDataReader so it
        // stays alive for the full read (the command must outlive the reader).
        var cmd = source.CreateCommand();
        cmd.CommandText = transform is null
            ? $"SELECT {columnList} FROM [{legacyTable.Replace("]", "]]", StringComparison.Ordinal)}]"
            : transform.Apply(columnList);
        var reader = await cmd.ExecuteReaderAsync(ct);
        return new CountingDataReader(reader, cmd);
    }

    private static async Task EnableIdentityInsertAsync(SqlConnection target, string table, bool on,
        CancellationToken ct)
    {
        var state = on ? "ON" : "OFF";
        await using var cmd = target.CreateCommand();
        cmd.CommandText = $"SET IDENTITY_INSERT [{table.Replace("]", "]]", StringComparison.Ordinal)}] {state}";
        await cmd.ExecuteNonQueryAsync(ct);
    }

    /// <summary>
    /// Wraps a SqlDataReader with a row counter and owns the command.
    /// Derives from <see cref="DbDataReader"/> so it can be passed directly to
    /// <see cref="SqlBulkCopy.WriteToServerAsync(DbDataReader, CancellationToken)"/>.
    /// </summary>
    private sealed class CountingDataReader : DbDataReader, IAsyncDisposable
    {
        private readonly SqlDataReader _inner;
        private readonly SqlCommand _command;

        public CountingDataReader(SqlDataReader inner, SqlCommand command)
        {
            _inner = inner;
            _command = command;
        }

        public long RowsRead { get; private set; }

        public override int Depth => _inner.Depth;
        public override int FieldCount => _inner.FieldCount;
        public override bool HasRows => _inner.HasRows;
        public override bool IsClosed => _inner.IsClosed;
        public override int RecordsAffected => _inner.RecordsAffected;

        public override object this[int ordinal] => _inner[ordinal];
        public override object this[string name] => _inner[name];

        public override bool GetBoolean(int ordinal) => _inner.GetBoolean(ordinal);
        public override byte GetByte(int ordinal) => _inner.GetByte(ordinal);
        public override long GetBytes(int ordinal, long dataOffset, byte[]? buffer, int bufferOffset, int length)
            => _inner.GetBytes(ordinal, dataOffset, buffer, bufferOffset, length);
        public override char GetChar(int ordinal) => _inner.GetChar(ordinal);
        public override long GetChars(int ordinal, long dataOffset, char[]? buffer, int bufferOffset, int length)
            => _inner.GetChars(ordinal, dataOffset, buffer, bufferOffset, length);
        public override string GetDataTypeName(int ordinal) => _inner.GetDataTypeName(ordinal);
        public override DateTime GetDateTime(int ordinal) => _inner.GetDateTime(ordinal);
        public override decimal GetDecimal(int ordinal) => _inner.GetDecimal(ordinal);
        public override double GetDouble(int ordinal) => _inner.GetDouble(ordinal);
        public override IEnumerator GetEnumerator() => _inner.GetEnumerator();
        public override Type GetFieldType(int ordinal) => _inner.GetFieldType(ordinal);
        public override float GetFloat(int ordinal) => _inner.GetFloat(ordinal);
        public override Guid GetGuid(int ordinal) => _inner.GetGuid(ordinal);
        public override short GetInt16(int ordinal) => _inner.GetInt16(ordinal);
        public override int GetInt32(int ordinal) => _inner.GetInt32(ordinal);
        public override long GetInt64(int ordinal) => _inner.GetInt64(ordinal);
        public override string GetName(int ordinal) => _inner.GetName(ordinal);
        public override int GetOrdinal(string name) => _inner.GetOrdinal(name);
        public override string GetString(int ordinal) => _inner.GetString(ordinal);
        public override object GetValue(int ordinal) => _inner.GetValue(ordinal);
        public override int GetValues(object[] values) => _inner.GetValues(values);
        public override bool IsDBNull(int ordinal) => _inner.IsDBNull(ordinal);
        public override bool NextResult() => _inner.NextResult();

        public override Task<bool> ReadAsync(CancellationToken cancellationToken)
            => ReadAsyncCore(cancellationToken);

        private async Task<bool> ReadAsyncCore(CancellationToken cancellationToken)
        {
            var read = await _inner.ReadAsync(cancellationToken);
            if (read) RowsRead++;
            return read;
        }

        public override bool Read()
        {
            var read = _inner.Read();
            if (read) RowsRead++;
            return read;
        }

        public override DataTable GetSchemaTable() => _inner.GetSchemaTable() ?? new DataTable();

        public override void Close() => _inner.Close();

        public override ValueTask DisposeAsync()
        {
            _inner.DisposeAsync().GetAwaiter().GetResult();
            _command.Dispose();
            GC.SuppressFinalize(this);
            return ValueTask.CompletedTask;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _inner.Dispose();
                _command.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
